/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyNftCollection {
        "theme": string;
        "user": string;
    }
}
declare global {
    interface HTMLMyNftCollectionElement extends Components.MyNftCollection, HTMLStencilElement {
    }
    var HTMLMyNftCollectionElement: {
        prototype: HTMLMyNftCollectionElement;
        new (): HTMLMyNftCollectionElement;
    };
    interface HTMLElementTagNameMap {
        "my-nft-collection": HTMLMyNftCollectionElement;
    }
}
declare namespace LocalJSX {
    interface MyNftCollection {
        "theme"?: string;
        "user"?: string;
    }
    interface IntrinsicElements {
        "my-nft-collection": MyNftCollection;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-nft-collection": LocalJSX.MyNftCollection & JSXBase.HTMLAttributes<HTMLMyNftCollectionElement>;
        }
    }
}
